# Generated by Django 2.2.3 on 2019-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litWorks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litwork',
            name='audioLocation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='litwork',
            name='docLocation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='litwork',
            name='picLocation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='litwork',
            name='vedioLocation',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
